"""complete

Revision ID: b209a9536f3e
Revises: 
Create Date: 2020-12-26 13:03:39.379509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b209a9536f3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Counsellor',
    sa.Column('c_email_id', sa.String(length=120), nullable=False),
    sa.Column('f_name', sa.String(length=250), nullable=False),
    sa.Column('l_name', sa.String(length=250), nullable=False),
    sa.Column('dept_id', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['Department.dept_id'], ),
    sa.PrimaryKeyConstraint('c_email_id')
    )
    op.create_table('Credentials',
    sa.Column('email_id', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('email_id')
    )
    op.create_table('Department',
    sa.Column('dept_id', sa.String(length=5), nullable=False),
    sa.Column('dept_name', sa.String(length=20), nullable=False),
    sa.Column('h_email_id', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['h_email_id'], ['Counsellor.c_email_id'], ),
    sa.PrimaryKeyConstraint('dept_id')
    )
    op.create_table('PhoneNumber',
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('phone_number')
    )
    op.create_table('Course',
    sa.Column('course_code', sa.String(length=10), nullable=False),
    sa.Column('course_name', sa.String(length=20), nullable=False),
    sa.Column('dept_id', sa.String(length=5), nullable=True),
    sa.Column('sem_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['Department.dept_id'], ),
    sa.PrimaryKeyConstraint('course_code')
    )
    op.create_table('PhoneNumbers',
    sa.Column('email_id', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['Credentials.email_id'], ),
    sa.ForeignKeyConstraint(['phone_number'], ['PhoneNumber.phone_number'], ),
    sa.PrimaryKeyConstraint('email_id', 'phone_number')
    )
    op.create_table('Student',
    sa.Column('s_email_id', sa.String(length=120), nullable=False),
    sa.Column('usn', sa.String(length=10), nullable=False),
    sa.Column('f_name', sa.String(length=250), nullable=False),
    sa.Column('l_name', sa.String(length=250), nullable=False),
    sa.Column('doj', sa.Date(), nullable=False),
    sa.Column('dept_id', sa.String(length=5), nullable=True),
    sa.Column('c_email_id', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['c_email_id'], ['Counsellor.c_email_id'], ),
    sa.ForeignKeyConstraint(['dept_id'], ['Department.dept_id'], ),
    sa.PrimaryKeyConstraint('s_email_id'),
    sa.UniqueConstraint('usn')
    )
    op.create_table('Parent',
    sa.Column('p_email_id', sa.String(length=120), nullable=False),
    sa.Column('f_name', sa.String(length=250), nullable=False),
    sa.Column('l_name', sa.String(length=250), nullable=False),
    sa.Column('c_email_id', sa.String(length=120), nullable=True),
    sa.Column('s_email_id', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['c_email_id'], ['Counsellor.c_email_id'], ),
    sa.ForeignKeyConstraint(['s_email_id'], ['Student.s_email_id'], ),
    sa.PrimaryKeyConstraint('p_email_id')
    )
    op.create_table('ProfessorCourseDetails',
    sa.Column('c_email_id', sa.String(length=120), nullable=False),
    sa.Column('course_code', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['c_email_id'], ['Counsellor.c_email_id'], ),
    sa.ForeignKeyConstraint(['course_code'], ['Course.course_code'], ),
    sa.PrimaryKeyConstraint('c_email_id', 'course_code')
    )
    op.create_table('StudentCourseDetails',
    sa.Column('s_email_id', sa.String(length=120), nullable=False),
    sa.Column('course_code', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['course_code'], ['Course.course_code'], ),
    sa.ForeignKeyConstraint(['s_email_id'], ['Student.s_email_id'], ),
    sa.PrimaryKeyConstraint('s_email_id', 'course_code', 'date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('StudentCourseDetails')
    op.drop_table('ProfessorCourseDetails')
    op.drop_table('Parent')
    op.drop_table('Student')
    op.drop_table('PhoneNumbers')
    op.drop_table('Course')
    op.drop_table('PhoneNumber')
    op.drop_table('Department')
    op.drop_table('Credentials')
    op.drop_table('Counsellor')
    # ### end Alembic commands ###
